keys:
    - base_urls:
        anthropic: https://api.deepseek.com/anthropic
        openai: https://api.deepseek.com
      enabled: true
      format: openai
      models:
        - alias: v4-pro
          name: deepseek-v4-pro
          priority: 0
        - alias: v4-flash
          name: deepseek-v4-flash
          priority: 0
        - alias: chat
          name: deepseek-chat
          priority: 0
        - alias: r1
          name: deepseek-reasoner
          priority: 0
      name: deepseek-1
      provider: deepseek
      secret: sk-83594ff687494ddb9684cac00c49a882
